import React from 'react';
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

interface Props {
  metrics: { cpu: any; memory: any; disk: any[]; network: any; processes: any[] };
  onDiagnose: () => void;
}

const cpuGauge = (cpu: any) => [{ name: 'Used', value: cpu.percent }, { name: 'Free', value: 100 - cpu.percent }];
const memGauge = (mem: any) => [{ name: 'Used', value: mem.percent }, { name: 'Free', value: 100 - mem.percent }];
const getColor = (pct: number, t = [90, 70]) => pct > t[0] ? 'var(--danger)' : pct > t[1] ? 'var(--warning)' : 'var(--success)';
const getGaugeFill = (pct: number, t = [90, 70]) => pct > t[0] ? '#f85149' : pct > t[1] ? '#d29922' : '#3fb950';
const tcpStateData = (s: Record<string, number>) => Object.entries(s).map(([name, value]) => ({ name, value }));

export default function MonitoringPanel({ metrics, onDiagnose }: Props) {
  const { cpu, memory, disk, network, processes } = metrics;
  return (
    <div className="dashboard">
      <div className="summary-bar">
        <div className="summary-item"><div className="summary-icon cpu">⚡</div><div className="summary-info"><div className="summary-title">CPU</div><div className="summary-val" style={{ color: getColor(cpu.percent) }}>{cpu.percent}%</div><div className="summary-detail">{cpu.count} cores · {cpu.frequency_mhz} MHz</div></div></div>
        <div className="summary-item"><div className="summary-icon mem">🧠</div><div className="summary-info"><div className="summary-title">Memory</div><div className="summary-val" style={{ color: getColor(memory.percent, [90, 80]) }}>{memory.percent}%</div><div className="summary-detail">{memory.used_mb} / {memory.total_mb} MB</div></div></div>
        <div className="summary-item"><div className="summary-icon disk">💾</div><div className="summary-info"><div className="summary-title">Disk</div><div className="summary-val" style={{ color: getColor(disk[0]?.percent || 0, [85, 70]) }}>{disk[0]?.percent || 0}%</div><div className="summary-detail">{disk[0]?.mountpoint || '/'} · {disk[0]?.fstype || 'ext4'}</div></div></div>
        <div className="summary-item"><div className="summary-icon net">🌐</div><div className="summary-info"><div className="summary-title">Network</div><div className="summary-val">{network.connections_count}</div><div className="summary-detail">↑{network.bytes_sent_mb} ↓{network.bytes_recv_mb} MB</div></div></div>
      </div>
      <div className="card"><div className="card-header"><span className="card-title">CPU Usage</span><span className="card-value" style={{ color: getColor(cpu.percent) }}>{cpu.percent}%</span></div><div className="card-body"><div className="chart-container"><ResponsiveContainer width="100%" height={130}><PieChart><Pie data={cpuGauge(cpu)} cx="50%" cy="50%" innerRadius={40} outerRadius={58} dataKey="value" paddingAngle={3} strokeWidth={0}><Cell fill={getGaugeFill(cpu.percent)} /><Cell fill="var(--border)" /></Pie></PieChart></ResponsiveContainer><div className="gauge-center"><div className="gauge-value" style={{ color: getColor(cpu.percent) }}>{cpu.percent}%</div><div className="gauge-label">Usage</div></div></div><div className="metrics-row"><div className="metric-item"><span className="metric-label">Load</span><span className="metric-value">{cpu.load_1m} / {cpu.load_5m} / {cpu.load_15m}</span></div><div className="metric-item"><span className="metric-label">Cores</span><span className="metric-value">{cpu.count}</span></div></div>{cpu.percent > 90 && <button className="diagnose-btn" onClick={onDiagnose}>⚠ Diagnose</button>}</div></div>
      <div className="card"><div className="card-header"><span className="card-title">Memory</span><span className="card-value" style={{ color: getColor(memory.percent, [90, 80]) }}>{memory.percent}%</span></div><div className="card-body"><div className="chart-container"><ResponsiveContainer width="100%" height={130}><PieChart><Pie data={memGauge(memory)} cx="50%" cy="50%" innerRadius={40} outerRadius={58} dataKey="value" paddingAngle={3} strokeWidth={0}><Cell fill={getGaugeFill(memory.percent, [90, 80])} /><Cell fill="var(--border)" /></Pie></PieChart></ResponsiveContainer><div className="gauge-center"><div className="gauge-value" style={{ color: getColor(memory.percent, [90, 80]) }}>{memory.percent}%</div><div className="gauge-label">Usage</div></div></div><div className="metrics-row"><div className="metric-item"><span className="metric-label">Used</span><span className="metric-value">{memory.used_mb} MB</span></div><div className="metric-item"><span className="metric-label">Free</span><span className="metric-value">{memory.available_mb} MB</span></div></div>{memory.percent > 90 && <button className="diagnose-btn" onClick={onDiagnose}>⚠ Diagnose</button>}</div></div>
      <div className="card card-wide"><div className="card-header"><span className="card-title">Disk Partitions</span></div><div className="card-body"><div className="disk-list">{disk.map((d: any, i: number) => (<div key={i} className="disk-item"><div className="disk-info"><span className="disk-mount">{d.mountpoint}</span><span className="disk-type">{d.fstype}</span></div><div className="disk-bar-container"><div className="disk-bar" style={{ width: `${d.percent}%`, backgroundColor: d.percent > 85 ? '#f85149' : d.percent > 70 ? '#d29922' : '#3fb950' }} /></div><span className="disk-percent" style={{ color: getColor(d.percent, [85, 70]) }}>{d.percent}%</span><span className="disk-size">{d.used_gb}/{d.total_gb} GB</span></div>))}</div></div></div>
      <div className="card card-wide"><div className="card-header"><span className="card-title">Network</span></div><div className="card-body"><div className="network-stats"><div className="net-stat"><div className="net-stat-value">{network.bytes_sent_mb}</div><div className="net-stat-label">Sent (MB)</div></div><div className="net-stat"><div className="net-stat-value">{network.bytes_recv_mb}</div><div className="net-stat-label">Recv (MB)</div></div><div className="net-stat"><div className="net-stat-value">{network.connections_count}</div><div className="net-stat-label">Connections</div></div></div>{Object.keys(network.tcp_states || {}).length > 0 && (<ResponsiveContainer width="100%" height={100}><BarChart data={tcpStateData(network.tcp_states)}><CartesianGrid strokeDasharray="3 3" stroke="var(--border-light)" /><XAxis dataKey="name" stroke="var(--text-tertiary)" fontSize={10} tickLine={false} /><YAxis stroke="var(--text-tertiary)" fontSize={10} tickLine={false} axisLine={false} /><Tooltip contentStyle={{ backgroundColor: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 'var(--radius-sm)', fontSize: 12 }} /><Bar dataKey="value" fill="var(--accent)" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer>)}</div></div>
      <div className="card card-full"><div className="card-header"><span className="card-title">Top Processes (by Memory)</span></div><div className="card-body no-padding"><table className="process-table"><thead><tr><th>PID</th><th>Name</th><th>CPU %</th><th>MEM %</th><th>Status</th></tr></thead><tbody>{processes.map((p: any, i: number) => (<tr key={i}><td>{p.pid}</td><td className="process-name">{p.name}</td><td>{p.cpu_percent}%</td><td style={{ color: p.memory_percent > 5 ? 'var(--danger)' : 'inherit' }}>{p.memory_percent}%</td><td><span className={`status-badge ${p.status === 'running' ? 'status-running' : 'status-sleeping'}`}>{p.status}</span></td></tr>))}</tbody></table></div></div>
    </div>
  );
}
